// Generated by LiveScript 1.2.0
require.config({
  baseUrl: 'static/js/',
  paths: {
    uiloading: '/uiload'
  }
});
require(['uiloading'], function(){
  var x$;
  x$ = angular.module('main', ['uiloading']);
  x$.controller('main', ['$scope', '$interval', '$timeout'].concat(function($scope, $interval, $timeout){
    console.log('main');
    $scope.xx = 1;
    $scope.infinity = {
      circle: '#000',
      line: '#f00',
      speed: '1s'
    };
    $scope.gif = new GIF({
      workers: 2,
      quality: 10,
      transparent: 0xFFFF00
    });
    return $scope.$watch('a', function(){
      var timer;
      if ($scope.a) {
        $scope.step = 0;
        return timer = $interval(function(){
          $scope.a.step($scope.step);
          return html2canvas($scope.a.node, {
            onrendered: function(it){
              $scope.step += 100;
              $scope.gif.addFrame(it, {
                delay: 100,
                copy: true
              });
              if ($scope.step === 1000) {
                $interval.cancel(timer);
                $scope.gif.on('finished', function(blob){
                  var reader;
                  reader = new window.FileReader();
                  reader.readAsDataURL(blob);
                  return reader.onloadend = function(){
                    var img;
                    img = document.createElement("img");
                    console.log(reader.result);
                    img.src = reader.result;
                    return $(document.body).append($(img));
                  };
                });
                return $scope.gif.render();
              }
            }
          });
        }, 2000);
      }
    });
  }));
  return angular.bootstrap($("body"), ['main']);
});