// Generated by LiveScript 1.2.0
require.config({
  baseUrl: 'static/js/',
  paths: {
    uiloading: '/uiload'
  }
});
require(['uiloading'], function(){
  var x$;
  x$ = angular.module('main', ['uiloading']);
  x$.controller('main', ['$scope', '$timeout', '$interval'].concat(function($scope, $timeout, $interval){
    $scope.delay = 0;
    return $scope.$watch('demoLoader', function(){
      if ($scope.demoLoader) {
        return $timeout(function(){
          $scope.demoLoader.start();
          return $interval(function(){
            $scope.demoLoader.step($scope.delay);
            return $scope.delay = ($scope.delay + 30) % 1000;
          }, 30);
        }, 1000);
      }
    });
  }));
  return angular.bootstrap($("body"), ['main']);
});