// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('uiloading', []);
x$.factory('uiloadtype', function(){
  return {
    spin: '<div class="uil-spin">' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '<div><div></div></div>' + '</div>',
    circle: '<div class="uil-circle">' + '<div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>' + '</div>',
    reload: '<div class="uil-reload"></div>',
    pie: '<div class="uil-pie">' + '<div><div></div></div><div><div></div></div><div><div></div></div>' + '</div>',
    pacman: '<div class="uil-pacman">' + '<div><div></div></div><div><div></div></div><div><div></div></div>' + '</div>'
  };
});
x$.directive('uiload', function(uiloadtype){
  return {
    restrict: 'E',
    template: "",
    link: function(scope, e, attrs, ctrl){
      return e.html(uiloadtype[attrs['type']] || "");
    }
  };
});